/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './**/*.php',
    './blocks/**/*.js',
    './assets/js/*.js',
    '!./node_modules/**',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        'secondary-fixed': '#dde1ff',
        'surface-bright': '#fcf9f8',
        'on-primary': '#ffffff',
        outline: '#73777f',
        secondary: '#194ae4',
        'on-tertiary-container': '#4a3f0f',
        'on-primary-fixed-variant': '#234871',
        'surface-container': '#f0eded',
        primary: '#001b35',
        'on-secondary-fixed-variant': '#0035bd',
        'on-surface-variant': '#43474e',
        'outline-variant': '#c3c6cf',
        'on-secondary-container': '#fffbff',
        'surface-dim': '#dcd9d9',
        background: '#fcf9f8',
        'surface-variant': '#e4e2e1',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-container': '#bbab70',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#221b00',
        surface: '#fcf9f8',
        'primary-fixed': '#d2e4ff',
        'inverse-surface': '#303030',
        'secondary-container': '#3e66fe',
        'secondary-fixed-dim': '#b8c3ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#f4e2a2',
        'on-tertiary-fixed-variant': '#524616',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#a6c9f8',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'on-primary-container': '#7699c5',
        'surface-tint': '#3d608a',
        'tertiary-fixed-dim': '#d7c689',
        error: '#ba1a1a',
        'inverse-primary': '#a6c9f8',
        'inverse-on-surface': '#f3f0f0',
        'primary-container': '#003057',
        'on-primary-fixed': '#001c37',
        'on-background': '#1b1c1c',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'on-secondary-fixed': '#001355',
        tertiary: '#6b5e2b',
        'on-surface': '#1b1c1c',
      },
      borderRadius: {
        action: '0.5rem',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: true,
  },
  safelist: [],
};
